---
title: "**R-sig-meta-analysis Topics and FAQ**"
author: Wolfgang Viechtbauer and Others
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    # theme: yeti
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 1
    highlight: haddock
    #code_folding: show
    df_print: default # default, kable, tibble, paged
---

# Introduction

The [R-sig-meta-analysis mailing list](https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis) is a mailing list for discussing the use of the statistical software package [R](https://www.r-project.org) for [meta-analysis](https://en.wikipedia.org/wiki/Meta-analysis).

Discussions on the list often revolve around repeating topics. One can browse the [mailing list archives](https://stat.ethz.ch/pipermail/r-sig-meta-analysis/) or use search engines like [Google](https://www.google.com/search?hl=EN&source=hp&q=site:https://stat.ethz.ch/pipermail/r-sig-meta-analysis
) or [DuckDuckGo](https://duckduckgo.com/?q=site:https://stat.ethz.ch/pipermail/r-sig-meta-analysis&ia=web) to find posts in the archives relevant to one's interest. This still requires some digging.

The purpose of this page is to provide pointers to relevant posts pertaining to various topics. Note that links to relevant posts from the archives may take you to the first post in a thread, which typically raises a question/issue. Pertinent answers can then be found in the responses to this post.

# Topics

### What R packages are there for meta-analysis?

Take a look at the [CRAN Task View: Meta-Analysis](https://cran.r-project.org/web/views/MetaAnalysis.html) which provides a very detailed overview of R packages for meta-analysis and their purposes.

### What to do when one cannot compute the sampling variances for some studies

Standard meta-analytic models use as input the effect size estimates and the corresponding sampling variances (or the standard errors). At times, it may be difficult to extract the information needed to compute the sampling variances / standard errors for some of the studies. Some possible approaches one can consider in this case are discussed here:

- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2017-June/000011.html

### Meta-analysis of survival data (KM estimates)

- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2017-June/000008.html

### The Freeman-Tukey double arcsine transformation and its back-transformation

- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2017-July/000026.html

### Definition / computation of $I^2$, $R^2$, and $I^2$ in meta-regression models

- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2021-October/003447.html

### Multilevel and multivariate meta-analysis for dependent effect sizes

- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2017-August/000131.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-January/000483.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-February/000638.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-April/000735.html
- https://stat.ethz.ch/pipermail/r-sig-meta-analysis/2017-August/000094.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2019-March/001479.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2019-September/001747.html

### Generalized Linear Models and meta-analysis

- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-January/

### Q-Statistic/Chi-square/F-test for Between-Subgroup Heterogeneity

- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-July/000912.html
- https://hypatia.math.ethz.ch/pipermail/r-sig-meta-analysis/2018-October/001156.html